[build]
  command  = "CI=false npm run build"

# REACT ROUTER
[[redirects]]
  from = "/*"
  to = "/"
  status = 200


  [[redirects]]
  from = "/api/*"
  to = "https://mitivelane.herokuapp.com/:splat"
  status = 200