export const dummy_session = [
    {
      id: 1,
      name: "Giann",
      message: "Created list for ayuda.",
      action: "create",
      createdAt: "10-11-2021",
      module: "Organization",
    },
    {
      id: 2,
      name: "Giann",
      message: "Deleted 5 users.",
      action: "delete",
      createdAt: "10-16-2021",
      module: "User",
    },
    {
      id: 3,
      name: "Rojhon",
      message: "Edited mothly funds for October 2021.",
      action: "update",
      createdAt: "10-21-2021",
      module: "Organization",
    },
    {
      id: 4,
      name: "Von",
      message: "Created list for good employees for this month.",
      action: "create",
      createdAt: "10-21-2021",
      module: "Organization",
    },
    {
      id: 2,
      name: "Giann",
      message: "Deleted 2 documents.",
      action: "delete",
      createdAt: "10-16-2021",
      module: "Blotter",
    },
    {
      id: 2,
      name: "Giann",
      message: "Deleted 5 users.",
      action: "delete",
      createdAt: "10-16-2021",
      module: "User",
    },
    {
      id: 3,
      name: "Rojhon",
      message: "Edited mothly funds for October 2021.",
      action: "update",
      createdAt: "10-21-2021",
      module: "Organization",
    },
    {
      id: 4,
      name: "Von",
      message: "Created list for good employees for this month.",
      action: "create",
      createdAt: "10-21-2021",
      module: "Organization",
    },
    {
      id: 2,
      name: "Giann",
      message: "Deleted 2 documents.",
      action: "delete",
      createdAt: "10-16-2021",
      module: "Blotter",
    },
    {
      id: 2,
      name: "Giann",
      message: "Deleted 5 users.",
      action: "delete",
      createdAt: "10-16-2021",
      module: "User",
    },
    {
      id: 3,
      name: "Rojhon",
      message: "Edited mothly funds for October 2021.",
      action: "update",
      createdAt: "10-21-2021",
      module: "Organization",
    },
    {
      id: 4,
      name: "Von",
      message: "Created list for good employees for this month.",
      action: "create",
      createdAt: "10-21-2021",
      module: "Organization",
    },
    {
      id: 2,
      name: "Giann",
      message: "Deleted 2 documents.",
      action: "delete",
      createdAt: "10-16-2021",
      module: "Blotter",
    },
  ];